package com.drool.model;

import java.util.Date;
import javax.xml.bind.annotation.XmlAttribute;  
import javax.xml.bind.annotation.XmlElement;  
import javax.xml.bind.annotation.XmlRootElement;


public class IsoField {
	String MSG_TYPE;
	String PRIMARY_ACCOUNT_NUMBER;
	String PROCESSING_CODE;
	String AMOUNT_TRANSACTION;
	String AMOUNT_SETTLEMENT;
	String AMOUNT_CARDHOLDER_BILLING;
	String TRANSMISSION_DATE_AND_TIME;
	String AMOUNT_CARDHOLDER_BILLING_FEE;
	String CONVERSION_RATE_SETTLEMENT;
	String CONVERSION_RATE_CARDHOLDER_BILLING;
	String SYSTEM_TRACE_AUDIT_NUMBER;
	String TIME_LOCAL_TRANSACTION;
	String DATE_LOCAL_TRANSACTION;
	String DATE_EXPIRATION;
	String DATE_SETTLEMENT;
	String DATE_CONVERSION;
	String DATE_CAPTURE;
	String MERCHANTS_TYPE;
	String ACQUIRING_INSTITUTION_COUNTRY_CODE;
	String PAN_EXTENDED_COUNTRY_CODE;
	String FORWARDING_INSTITUTION_COUNTRY_CODE;
	String POINT_OF_SERVICE_ENTRY_MODE;
	String CARD_SEQUENCE_NUMBER;
	String NETWORK_INTERNATIONAL_IDENTIFIEER;
	String POINT_OF_SERVICE_CONDITION_CODE;
	String POINT_OF_SERVICE_PIN_CAPTURE_CODE;
	String AUTHORIZATION_IDENTIFICATION_RESP_LEN;
	String AMOUNT_TRANSACTION_FEE;
	String AMOUNT_SETTLEMENT_FEE;
	String AMOUNT_TRANSACTION_PROCESSING_FEE;
	String AMOUNT_SETTLEMENT_PROCESSING_FEE;
	String ACQUIRING_INSTITUTION_IDENT_CODE;
	String FORWARDING_INSTITUTION_IDENT_CODE;
	String PAN_EXTENDED;
	String TRACK_2_DATA;
	String TRACK_3_DATA;
	String RETRIEVAL_REFERENCE_NUMBER;
	String AUTHORIZATION_IDENTIFICATION_RESPONSE;
	String RESPONSE_CODE;
	String SERVICE_RESTRICTION_CODE;  
    String CARD_ACCEPTOR_TERMINAL_IDENTIFICACION;
    String CARD_ACCEPTOR_IDENTIFICATION_CODE;
    String CARD_ACCEPTOR_NAME_OR_LOCATION;
    String ADITIONAL_RESPONSE_DATA;
    String TRACK_1_DATA;
    String ADITIONAL_DATA_ISO;
    String ADITIONAL_DATA_NATIONAL;
    String ADITIONAL_DATA_PRIVATE;
    String CURRENCY_CODE_TRANSACTION;
    String CURRENCY_CODE_SETTLEMENT;
    String CURRENCY_CODE_CARDHOLDER_BILLING;
    String PIN_DATA;
    String SECURITY_RELATED_CONTROL_INFORMATION;
    String ADDITIONAL_AMOUNTS;
    String RESERVED_ISO_55;
    String RESERVED_ISO_56;
    String RESERVED_NATIONAL_57;
    String RESERVED_NATIONAL_58;
    String RESERVED_NATIONAL_59;
    String RESERVED_PRIVATE_60;
    String RESERVED_PRIVATE_61;
    String RESERVED_PRIVATE_62;
    String RESERVED_PRIVATE_63;
    String MESSAGE_AUTHENTICATION_CODE_FIELD;
    String BITMAP_EXTENDED;
    String SETTLEMENT_CODE;
    String EXTENDED_PAYMENT_CODE;
    String RECEIVING_INSTITUTION_COUNTRY_CODE;
    String SETTLEMENT_INSTITUTION_COUNTRY_CODE;
    String NETWORK_MANAGEMENT_INFORMATION_CODE;
    String MESSAGE_NUMBER;
    String MESSAGE_NUMBER_LAST;
    String DATE_ACTION;
    String CREDITS_NUMBER;
    String CREDITS_REVERSAL_NUMBER;
    String DEBITS_NUMBER;
    String DEBITS_REVERSAL_NUMBER;
    String TRANSFER_NUMBER;
    String TRANSFER_REVERSAL_NUMBER;
    String INQUIRIES_NUMBER;
    String AUTHORIZATION_NUMBER;
    String CREDITS_PROCESSING_FEE_AMOUNT;
    String CREDITS_TRANSACTION_FEE_AMOUNT;
    String DEBITS_PROCESSING_FEE_AMOUNT;
    String DEBITS_TRANSACTION_FEE_AMOUNT;
    String CREDITS_AMOUNT;
    String CREDITS_REVERSAL_AMOUNT;
    String DEBITS_AMOUNT;
    String DEBITS_REVERSAL_AMOUNT;
    String ORIGINAL_DATA_ELEMENTS;
    String FILE_UPDATE_CODE;
    String FILE_SECURITY_CODE;
    String RESPONSE_INDICATOR;
    String SERVICE_INDICATOR;
    String REPLACEMENT_AMOUNTS;
    String MESSAGE_SECURITY_CODE;
    String AMOUNT_NET_SETTLEMENT;
    String PAYEE;
    String SETTLEMENT_INSTITUTION_IDENT_CODE;
    String RECEIVING_INSTITUTION_IDENT_CODE;
    String FILE_NAME;
    String ACCOUNT_IDENTIFICATION_1;
    String ACCOUNT_IDENTIFICATION_2;
    String TRANSACTION_DESCRIPTION;
    String RESERVED_ISO_USE_105;
    String RESERVED_ISO_USE_106;
    String RESERVED_ISO_USE_107;
    String RESERVED_ISO_USE_108;
    String RESERVED_ISO_USE_109;
    String RESERVED_ISO_USE_110;
    String RESERVED_ISO_USE_111;
    String RESERVED_NATIONAL_USE_112;
    String RESERVED_NATIONAL_USE_113;
    String RESERVED_NATIONAL_USE_114;
    String RESERVED_NATIONAL_USE_115;
    String RESERVED_NATIONAL_USE_116;
    String RESERVED_NATIONAL_USE_117;
    String RESERVED_NATIONAL_USE_118;
    String RESERVED_NATIONAL_USE_119;
    String RESERVED_PRIVATE_USE_120;
    String RESERVED_PRIVATE_USE_121;
    String RESERVED_PRIVATE_USE_122;
    String RESERVED_PRIVATE_USE_123;
    String RESERVED_PRIVATE_USE_124;
    String RESERVED_PRIVATE_USE_125;
    String RESERVED_PRIVATE_USE_126;
    String RESERVED_PRIVATE_USE_127;
    String MAC_2;

	public String getMSG_TYPE() {
		return MSG_TYPE;
	}
	public void setMSG_TYPE(String mSG_TYPE) {
		MSG_TYPE = mSG_TYPE;
	}
	public String getPRIMARY_ACCOUNT_NUMBER() {
		return PRIMARY_ACCOUNT_NUMBER;
	}
	public void setPRIMARY_ACCOUNT_NUMBER(String pRIMARY_ACCOUNT_NUMBER) {
		PRIMARY_ACCOUNT_NUMBER = pRIMARY_ACCOUNT_NUMBER;
	}
	public String getPROCESSING_CODE() {
		return PROCESSING_CODE;
	}
	public void setPROCESSING_CODE(String pROCESSING_CODE) {
		PROCESSING_CODE = pROCESSING_CODE;
	}
	public String getAMOUNT_TRANSACTION() {
		return AMOUNT_TRANSACTION;
	}
	public void setAMOUNT_TRANSACTION(String aMOUNT_TRANSACTION) {
		AMOUNT_TRANSACTION = aMOUNT_TRANSACTION;
	}
	public String getAMOUNT_SETTLEMENT() {
		return AMOUNT_SETTLEMENT;
	}
	public void setAMOUNT_SETTLEMENT(String aMOUNT_SETTLEMENT) {
		AMOUNT_SETTLEMENT = aMOUNT_SETTLEMENT;
	}
	public String getAMOUNT_CARDHOLDER_BILLING() {
		return AMOUNT_CARDHOLDER_BILLING;
	}
	public void setAMOUNT_CARDHOLDER_BILLING(String aMOUNT_CARDHOLDER_BILLING) {
		AMOUNT_CARDHOLDER_BILLING = aMOUNT_CARDHOLDER_BILLING;
	}
	public String getTRANSMISSION_DATE_AND_TIME() {
		return TRANSMISSION_DATE_AND_TIME;
	}
	public void setTRANSMISSION_DATE_AND_TIME(String tRANSMISSION_DATE_AND_TIME) {
		TRANSMISSION_DATE_AND_TIME = tRANSMISSION_DATE_AND_TIME;
	}
	public String getAMOUNT_CARDHOLDER_BILLING_FEE() {
		return AMOUNT_CARDHOLDER_BILLING_FEE;
	}
	public void setAMOUNT_CARDHOLDER_BILLING_FEE(String aMOUNT_CARDHOLDER_BILLING_FEE) {
		AMOUNT_CARDHOLDER_BILLING_FEE = aMOUNT_CARDHOLDER_BILLING_FEE;
	}
	public String getCONVERSION_RATE_SETTLEMENT() {
		return CONVERSION_RATE_SETTLEMENT;
	}
	public void setCONVERSION_RATE_SETTLEMENT(String cONVERSION_RATE_SETTLEMENT) {
		CONVERSION_RATE_SETTLEMENT = cONVERSION_RATE_SETTLEMENT;
	}
	public String getCONVERSION_RATE_CARDHOLDER_BILLING() {
		return CONVERSION_RATE_CARDHOLDER_BILLING;
	}
	public void setCONVERSION_RATE_CARDHOLDER_BILLING(String cONVERSION_RATE_CARDHOLDER_BILLING) {
		CONVERSION_RATE_CARDHOLDER_BILLING = cONVERSION_RATE_CARDHOLDER_BILLING;
	}
	public String getSYSTEM_TRACE_AUDIT_NUMBER() {
		return SYSTEM_TRACE_AUDIT_NUMBER;
	}
	public void setSYSTEM_TRACE_AUDIT_NUMBER(String sYSTEM_TRACE_AUDIT_NUMBER) {
		SYSTEM_TRACE_AUDIT_NUMBER = sYSTEM_TRACE_AUDIT_NUMBER;
	}
	public String getTIME_LOCAL_TRANSACTION() {
		return TIME_LOCAL_TRANSACTION;
	}
	public void setTIME_LOCAL_TRANSACTION(String tIME_LOCAL_TRANSACTION) {
		TIME_LOCAL_TRANSACTION = tIME_LOCAL_TRANSACTION;
	}
	public String getDATE_LOCAL_TRANSACTION() {
		return DATE_LOCAL_TRANSACTION;
	}
	public void setDATE_LOCAL_TRANSACTION(String dATE_LOCAL_TRANSACTION) {
		DATE_LOCAL_TRANSACTION = dATE_LOCAL_TRANSACTION;
	}
	public String getDATE_EXPIRATION() {
		return DATE_EXPIRATION;
	}
	public void setDATE_EXPIRATION(String dATE_EXPIRATION) {
		DATE_EXPIRATION = dATE_EXPIRATION;
	}
	public String getDATE_SETTLEMENT() {
		return DATE_SETTLEMENT;
	}
	public void setDATE_SETTLEMENT(String dATE_SETTLEMENT) {
		DATE_SETTLEMENT = dATE_SETTLEMENT;
	}
	public String getDATE_CONVERSION() {
		return DATE_CONVERSION;
	}
	public void setDATE_CONVERSION(String dATE_CONVERSION) {
		DATE_CONVERSION = dATE_CONVERSION;
	}
	public String getDATE_CAPTURE() {
		return DATE_CAPTURE;
	}
	public void setDATE_CAPTURE(String dATE_CAPTURE) {
		DATE_CAPTURE = dATE_CAPTURE;
	}
	public String getMERCHANTS_TYPE() {
		return MERCHANTS_TYPE;
	}
	public void setMERCHANTS_TYPE(String mERCHANTS_TYPE) {
		MERCHANTS_TYPE = mERCHANTS_TYPE;
	}
	public String getACQUIRING_INSTITUTION_COUNTRY_CODE() {
		return ACQUIRING_INSTITUTION_COUNTRY_CODE;
	}
	public void setACQUIRING_INSTITUTION_COUNTRY_CODE(String aCQUIRING_INSTITUTION_COUNTRY_CODE) {
		ACQUIRING_INSTITUTION_COUNTRY_CODE = aCQUIRING_INSTITUTION_COUNTRY_CODE;
	}
	public String getPAN_EXTENDED_COUNTRY_CODE() {
		return PAN_EXTENDED_COUNTRY_CODE;
	}
	public void setPAN_EXTENDED_COUNTRY_CODE(String pAN_EXTENDED_COUNTRY_CODE) {
		PAN_EXTENDED_COUNTRY_CODE = pAN_EXTENDED_COUNTRY_CODE;
	}
	public String getFORWARDING_INSTITUTION_COUNTRY_CODE() {
		return FORWARDING_INSTITUTION_COUNTRY_CODE;
	}
	public void setFORWARDING_INSTITUTION_COUNTRY_CODE(String fORWARDING_INSTITUTION_COUNTRY_CODE) {
		FORWARDING_INSTITUTION_COUNTRY_CODE = fORWARDING_INSTITUTION_COUNTRY_CODE;
	}
	public String getPOINT_OF_SERVICE_ENTRY_MODE() {
		return POINT_OF_SERVICE_ENTRY_MODE;
	}
	public void setPOINT_OF_SERVICE_ENTRY_MODE(String pOINT_OF_SERVICE_ENTRY_MODE) {
		POINT_OF_SERVICE_ENTRY_MODE = pOINT_OF_SERVICE_ENTRY_MODE;
	}
	public String getCARD_SEQUENCE_NUMBER() {
		return CARD_SEQUENCE_NUMBER;
	}
	public void setCARD_SEQUENCE_NUMBER(String cARD_SEQUENCE_NUMBER) {
		CARD_SEQUENCE_NUMBER = cARD_SEQUENCE_NUMBER;
	}
	public String getNETWORK_INTERNATIONAL_IDENTIFIEER() {
		return NETWORK_INTERNATIONAL_IDENTIFIEER;
	}
	public void setNETWORK_INTERNATIONAL_IDENTIFIEER(String nETWORK_INTERNATIONAL_IDENTIFIEER) {
		NETWORK_INTERNATIONAL_IDENTIFIEER = nETWORK_INTERNATIONAL_IDENTIFIEER;
	}
	public String getPOINT_OF_SERVICE_CONDITION_CODE() {
		return POINT_OF_SERVICE_CONDITION_CODE;
	}
	public void setPOINT_OF_SERVICE_CONDITION_CODE(String pOINT_OF_SERVICE_CONDITION_CODE) {
		POINT_OF_SERVICE_CONDITION_CODE = pOINT_OF_SERVICE_CONDITION_CODE;
	}
	public String getPOINT_OF_SERVICE_PIN_CAPTURE_CODE() {
		return POINT_OF_SERVICE_PIN_CAPTURE_CODE;
	}
	public void setPOINT_OF_SERVICE_PIN_CAPTURE_CODE(String pOINT_OF_SERVICE_PIN_CAPTURE_CODE) {
		POINT_OF_SERVICE_PIN_CAPTURE_CODE = pOINT_OF_SERVICE_PIN_CAPTURE_CODE;
	}
	public String getAUTHORIZATION_IDENTIFICATION_RESP_LEN() {
		return AUTHORIZATION_IDENTIFICATION_RESP_LEN;
	}
	public void setAUTHORIZATION_IDENTIFICATION_RESP_LEN(String aUTHORIZATION_IDENTIFICATION_RESP_LEN) {
		AUTHORIZATION_IDENTIFICATION_RESP_LEN = aUTHORIZATION_IDENTIFICATION_RESP_LEN;
	}
	public String getAMOUNT_TRANSACTION_FEE() {
		return AMOUNT_TRANSACTION_FEE;
	}
	public void setAMOUNT_TRANSACTION_FEE(String aMOUNT_TRANSACTION_FEE) {
		AMOUNT_TRANSACTION_FEE = aMOUNT_TRANSACTION_FEE;
	}
	public String getAMOUNT_SETTLEMENT_FEE() {
		return AMOUNT_SETTLEMENT_FEE;
	}
	public void setAMOUNT_SETTLEMENT_FEE(String aMOUNT_SETTLEMENT_FEE) {
		AMOUNT_SETTLEMENT_FEE = aMOUNT_SETTLEMENT_FEE;
	}
	public String getAMOUNT_TRANSACTION_PROCESSING_FEE() {
		return AMOUNT_TRANSACTION_PROCESSING_FEE;
	}
	public void setAMOUNT_TRANSACTION_PROCESSING_FEE(String aMOUNT_TRANSACTION_PROCESSING_FEE) {
		AMOUNT_TRANSACTION_PROCESSING_FEE = aMOUNT_TRANSACTION_PROCESSING_FEE;
	}
	public String getAMOUNT_SETTLEMENT_PROCESSING_FEE() {
		return AMOUNT_SETTLEMENT_PROCESSING_FEE;
	}
	public void setAMOUNT_SETTLEMENT_PROCESSING_FEE(String aMOUNT_SETTLEMENT_PROCESSING_FEE) {
		AMOUNT_SETTLEMENT_PROCESSING_FEE = aMOUNT_SETTLEMENT_PROCESSING_FEE;
	}
	public String getACQUIRING_INSTITUTION_IDENT_CODE() {
		return ACQUIRING_INSTITUTION_IDENT_CODE;
	}
	public void setACQUIRING_INSTITUTION_IDENT_CODE(String aCQUIRING_INSTITUTION_IDENT_CODE) {
		ACQUIRING_INSTITUTION_IDENT_CODE = aCQUIRING_INSTITUTION_IDENT_CODE;
	}
	public String getFORWARDING_INSTITUTION_IDENT_CODE() {
		return FORWARDING_INSTITUTION_IDENT_CODE;
	}
	public void setFORWARDING_INSTITUTION_IDENT_CODE(String fORWARDING_INSTITUTION_IDENT_CODE) {
		FORWARDING_INSTITUTION_IDENT_CODE = fORWARDING_INSTITUTION_IDENT_CODE;
	}
	public String getPAN_EXTENDED() {
		return PAN_EXTENDED;
	}
	public void setPAN_EXTENDED(String pAN_EXTENDED) {
		PAN_EXTENDED = pAN_EXTENDED;
	}
	public String getTRACK_2_DATA() {
		return TRACK_2_DATA;
	}
	public void setTRACK_2_DATA(String tRACK_2_DATA) {
		TRACK_2_DATA = tRACK_2_DATA;
	}
	public String getTRACK_3_DATA() {
		return TRACK_3_DATA;
	}
	public void setTRACK_3_DATA(String tRACK_3_DATA) {
		TRACK_3_DATA = tRACK_3_DATA;
	}
	public String getRETRIEVAL_REFERENCE_NUMBER() {
		return RETRIEVAL_REFERENCE_NUMBER;
	}
	public void setRETRIEVAL_REFERENCE_NUMBER(String rETRIEVAL_REFERENCE_NUMBER) {
		RETRIEVAL_REFERENCE_NUMBER = rETRIEVAL_REFERENCE_NUMBER;
	}
	public String getAUTHORIZATION_IDENTIFICATION_RESPONSE() {
		return AUTHORIZATION_IDENTIFICATION_RESPONSE;
	}
	public void setAUTHORIZATION_IDENTIFICATION_RESPONSE(String aUTHORIZATION_IDENTIFICATION_RESPONSE) {
		AUTHORIZATION_IDENTIFICATION_RESPONSE = aUTHORIZATION_IDENTIFICATION_RESPONSE;
	}
	public String getRESPONSE_CODE() {
		return RESPONSE_CODE;
	}
	public void setRESPONSE_CODE(String rESPONSE_CODE) {
		RESPONSE_CODE = rESPONSE_CODE;
	}
	public String getSERVICE_RESTRICTION_CODE() {
		return SERVICE_RESTRICTION_CODE;
	}
	public void setSERVICE_RESTRICTION_CODE(String sERVICE_RESTRICTION_CODE) {
		SERVICE_RESTRICTION_CODE = sERVICE_RESTRICTION_CODE;
	}
	public String getCARD_ACCEPTOR_TERMINAL_IDENTIFICACION() {
		return CARD_ACCEPTOR_TERMINAL_IDENTIFICACION;
	}
	public void setCARD_ACCEPTOR_TERMINAL_IDENTIFICACION(String cARD_ACCEPTOR_TERMINAL_IDENTIFICACION) {
		CARD_ACCEPTOR_TERMINAL_IDENTIFICACION = cARD_ACCEPTOR_TERMINAL_IDENTIFICACION;
	}
	public String getCARD_ACCEPTOR_IDENTIFICATION_CODE() {
		return CARD_ACCEPTOR_IDENTIFICATION_CODE;
	}
	public void setCARD_ACCEPTOR_IDENTIFICATION_CODE(String cARD_ACCEPTOR_IDENTIFICATION_CODE) {
		CARD_ACCEPTOR_IDENTIFICATION_CODE = cARD_ACCEPTOR_IDENTIFICATION_CODE;
	}
	public String getCARD_ACCEPTOR_NAME_OR_LOCATION() {
		return CARD_ACCEPTOR_NAME_OR_LOCATION;
	}
	public void setCARD_ACCEPTOR_NAME_OR_LOCATION(String cARD_ACCEPTOR_NAME_OR_LOCATION) {
		CARD_ACCEPTOR_NAME_OR_LOCATION = cARD_ACCEPTOR_NAME_OR_LOCATION;
	}
	public String getADITIONAL_RESPONSE_DATA() {
		return ADITIONAL_RESPONSE_DATA;
	}
	public void setADITIONAL_RESPONSE_DATA(String aDITIONAL_RESPONSE_DATA) {
		ADITIONAL_RESPONSE_DATA = aDITIONAL_RESPONSE_DATA;
	}
	public String getTRACK_1_DATA() {
		return TRACK_1_DATA;
	}
	public void setTRACK_1_DATA(String tRACK_1_DATA) {
		TRACK_1_DATA = tRACK_1_DATA;
	}
	public String getADITIONAL_DATA_ISO() {
		return ADITIONAL_DATA_ISO;
	}
	public void setADITIONAL_DATA_ISO(String aDITIONAL_DATA_ISO) {
		ADITIONAL_DATA_ISO = aDITIONAL_DATA_ISO;
	}
	public String getADITIONAL_DATA_NATIONAL() {
		return ADITIONAL_DATA_NATIONAL;
	}
	public void setADITIONAL_DATA_NATIONAL(String aDITIONAL_DATA_NATIONAL) {
		ADITIONAL_DATA_NATIONAL = aDITIONAL_DATA_NATIONAL;
	}
	public String getADITIONAL_DATA_PRIVATE() {
		return ADITIONAL_DATA_PRIVATE;
	}
	public void setADITIONAL_DATA_PRIVATE(String aDITIONAL_DATA_PRIVATE) {
		ADITIONAL_DATA_PRIVATE = aDITIONAL_DATA_PRIVATE;
	}
	public String getCURRENCY_CODE_TRANSACTION() {
		return CURRENCY_CODE_TRANSACTION;
	}
	public void setCURRENCY_CODE_TRANSACTION(String cURRENCY_CODE_TRANSACTION) {
		CURRENCY_CODE_TRANSACTION = cURRENCY_CODE_TRANSACTION;
	}
	public String getCURRENCY_CODE_SETTLEMENT() {
		return CURRENCY_CODE_SETTLEMENT;
	}
	public void setCURRENCY_CODE_SETTLEMENT(String cURRENCY_CODE_SETTLEMENT) {
		CURRENCY_CODE_SETTLEMENT = cURRENCY_CODE_SETTLEMENT;
	}
	public String getCURRENCY_CODE_CARDHOLDER_BILLING() {
		return CURRENCY_CODE_CARDHOLDER_BILLING;
	}
	public void setCURRENCY_CODE_CARDHOLDER_BILLING(String cURRENCY_CODE_CARDHOLDER_BILLING) {
		CURRENCY_CODE_CARDHOLDER_BILLING = cURRENCY_CODE_CARDHOLDER_BILLING;
	}
	public String getPIN_DATA() {
		return PIN_DATA;
	}
	public void setPIN_DATA(String pIN_DATA) {
		PIN_DATA = pIN_DATA;
	}
	public String getSECURITY_RELATED_CONTROL_INFORMATION() {
		return SECURITY_RELATED_CONTROL_INFORMATION;
	}
	public void setSECURITY_RELATED_CONTROL_INFORMATION(String sECURITY_RELATED_CONTROL_INFORMATION) {
		SECURITY_RELATED_CONTROL_INFORMATION = sECURITY_RELATED_CONTROL_INFORMATION;
	}
	public String getADDITIONAL_AMOUNTS() {
		return ADDITIONAL_AMOUNTS;
	}
	public void setADDITIONAL_AMOUNTS(String aDDITIONAL_AMOUNTS) {
		ADDITIONAL_AMOUNTS = aDDITIONAL_AMOUNTS;
	}
	public String getRESERVED_ISO_55() {
		return RESERVED_ISO_55;
	}
	public void setRESERVED_ISO_55(String rESERVED_ISO_55) {
		RESERVED_ISO_55 = rESERVED_ISO_55;
	}
	public String getRESERVED_ISO_56() {
		return RESERVED_ISO_56;
	}
	public void setRESERVED_ISO_56(String rESERVED_ISO_56) {
		RESERVED_ISO_56 = rESERVED_ISO_56;
	}
	public String getRESERVED_NATIONAL_57() {
		return RESERVED_NATIONAL_57;
	}
	public void setRESERVED_NATIONAL_57(String rESERVED_NATIONAL_57) {
		RESERVED_NATIONAL_57 = rESERVED_NATIONAL_57;
	}
	public String getRESERVED_NATIONAL_58() {
		return RESERVED_NATIONAL_58;
	}
	public void setRESERVED_NATIONAL_58(String rESERVED_NATIONAL_58) {
		RESERVED_NATIONAL_58 = rESERVED_NATIONAL_58;
	}
	public String getRESERVED_NATIONAL_59() {
		return RESERVED_NATIONAL_59;
	}
	public void setRESERVED_NATIONAL_59(String rESERVED_NATIONAL_59) {
		RESERVED_NATIONAL_59 = rESERVED_NATIONAL_59;
	}
	public String getRESERVED_PRIVATE_60() {
		return RESERVED_PRIVATE_60;
	}
	public void setRESERVED_PRIVATE_60(String rESERVED_PRIVATE_60) {
		RESERVED_PRIVATE_60 = rESERVED_PRIVATE_60;
	}
	public String getRESERVED_PRIVATE_61() {
		return RESERVED_PRIVATE_61;
	}
	public void setRESERVED_PRIVATE_61(String rESERVED_PRIVATE_61) {
		RESERVED_PRIVATE_61 = rESERVED_PRIVATE_61;
	}
	public String getRESERVED_PRIVATE_62() {
		return RESERVED_PRIVATE_62;
	}
	public void setRESERVED_PRIVATE_62(String rESERVED_PRIVATE_62) {
		RESERVED_PRIVATE_62 = rESERVED_PRIVATE_62;
	}
	public String getRESERVED_PRIVATE_63() {
		return RESERVED_PRIVATE_63;
	}
	public void setRESERVED_PRIVATE_63(String rESERVED_PRIVATE_63) {
		RESERVED_PRIVATE_63 = rESERVED_PRIVATE_63;
	}
	public String getMESSAGE_AUTHENTICATION_CODE_FIELD() {
		return MESSAGE_AUTHENTICATION_CODE_FIELD;
	}
	public void setMESSAGE_AUTHENTICATION_CODE_FIELD(String mESSAGE_AUTHENTICATION_CODE_FIELD) {
		MESSAGE_AUTHENTICATION_CODE_FIELD = mESSAGE_AUTHENTICATION_CODE_FIELD;
	}
	public String getBITMAP_EXTENDED() {
		return BITMAP_EXTENDED;
	}
	public void setBITMAP_EXTENDED(String bITMAP_EXTENDED) {
		BITMAP_EXTENDED = bITMAP_EXTENDED;
	}
	public String getSETTLEMENT_CODE() {
		return SETTLEMENT_CODE;
	}
	public void setSETTLEMENT_CODE(String sETTLEMENT_CODE) {
		SETTLEMENT_CODE = sETTLEMENT_CODE;
	}
	public String getEXTENDED_PAYMENT_CODE() {
		return EXTENDED_PAYMENT_CODE;
	}
	public void setEXTENDED_PAYMENT_CODE(String eXTENDED_PAYMENT_CODE) {
		EXTENDED_PAYMENT_CODE = eXTENDED_PAYMENT_CODE;
	}
	public String getRECEIVING_INSTITUTION_COUNTRY_CODE() {
		return RECEIVING_INSTITUTION_COUNTRY_CODE;
	}
	public void setRECEIVING_INSTITUTION_COUNTRY_CODE(String rECEIVING_INSTITUTION_COUNTRY_CODE) {
		RECEIVING_INSTITUTION_COUNTRY_CODE = rECEIVING_INSTITUTION_COUNTRY_CODE;
	}
	public String getSETTLEMENT_INSTITUTION_COUNTRY_CODE() {
		return SETTLEMENT_INSTITUTION_COUNTRY_CODE;
	}
	public void setSETTLEMENT_INSTITUTION_COUNTRY_CODE(String sETTLEMENT_INSTITUTION_COUNTRY_CODE) {
		SETTLEMENT_INSTITUTION_COUNTRY_CODE = sETTLEMENT_INSTITUTION_COUNTRY_CODE;
	}
	public String getNETWORK_MANAGEMENT_INFORMATION_CODE() {
		return NETWORK_MANAGEMENT_INFORMATION_CODE;
	}
	public void setNETWORK_MANAGEMENT_INFORMATION_CODE(String nETWORK_MANAGEMENT_INFORMATION_CODE) {
		NETWORK_MANAGEMENT_INFORMATION_CODE = nETWORK_MANAGEMENT_INFORMATION_CODE;
	}
	public String getMESSAGE_NUMBER() {
		return MESSAGE_NUMBER;
	}
	public void setMESSAGE_NUMBER(String mESSAGE_NUMBER) {
		MESSAGE_NUMBER = mESSAGE_NUMBER;
	}
	public String getMESSAGE_NUMBER_LAST() {
		return MESSAGE_NUMBER_LAST;
	}
	public void setMESSAGE_NUMBER_LAST(String mESSAGE_NUMBER_LAST) {
		MESSAGE_NUMBER_LAST = mESSAGE_NUMBER_LAST;
	}
	public String getDATE_ACTION() {
		return DATE_ACTION;
	}
	public void setDATE_ACTION(String dATE_ACTION) {
		DATE_ACTION = dATE_ACTION;
	}
	public String getCREDITS_NUMBER() {
		return CREDITS_NUMBER;
	}
	public void setCREDITS_NUMBER(String cREDITS_NUMBER) {
		CREDITS_NUMBER = cREDITS_NUMBER;
	}
	public String getCREDITS_REVERSAL_NUMBER() {
		return CREDITS_REVERSAL_NUMBER;
	}
	public void setCREDITS_REVERSAL_NUMBER(String cREDITS_REVERSAL_NUMBER) {
		CREDITS_REVERSAL_NUMBER = cREDITS_REVERSAL_NUMBER;
	}
	public String getDEBITS_NUMBER() {
		return DEBITS_NUMBER;
	}
	public void setDEBITS_NUMBER(String dEBITS_NUMBER) {
		DEBITS_NUMBER = dEBITS_NUMBER;
	}
	public String getDEBITS_REVERSAL_NUMBER() {
		return DEBITS_REVERSAL_NUMBER;
	}
	public void setDEBITS_REVERSAL_NUMBER(String dEBITS_REVERSAL_NUMBER) {
		DEBITS_REVERSAL_NUMBER = dEBITS_REVERSAL_NUMBER;
	}
	public String getTRANSFER_NUMBER() {
		return TRANSFER_NUMBER;
	}
	public void setTRANSFER_NUMBER(String tRANSFER_NUMBER) {
		TRANSFER_NUMBER = tRANSFER_NUMBER;
	}
	public String getTRANSFER_REVERSAL_NUMBER() {
		return TRANSFER_REVERSAL_NUMBER;
	}
	public void setTRANSFER_REVERSAL_NUMBER(String tRANSFER_REVERSAL_NUMBER) {
		TRANSFER_REVERSAL_NUMBER = tRANSFER_REVERSAL_NUMBER;
	}
	public String getINQUIRIES_NUMBER() {
		return INQUIRIES_NUMBER;
	}
	public void setINQUIRIES_NUMBER(String iNQUIRIES_NUMBER) {
		INQUIRIES_NUMBER = iNQUIRIES_NUMBER;
	}
	public String getAUTHORIZATION_NUMBER() {
		return AUTHORIZATION_NUMBER;
	}
	public void setAUTHORIZATION_NUMBER(String aUTHORIZATION_NUMBER) {
		AUTHORIZATION_NUMBER = aUTHORIZATION_NUMBER;
	}
	public String getCREDITS_PROCESSING_FEE_AMOUNT() {
		return CREDITS_PROCESSING_FEE_AMOUNT;
	}
	public void setCREDITS_PROCESSING_FEE_AMOUNT(String cREDITS_PROCESSING_FEE_AMOUNT) {
		CREDITS_PROCESSING_FEE_AMOUNT = cREDITS_PROCESSING_FEE_AMOUNT;
	}
	public String getCREDITS_TRANSACTION_FEE_AMOUNT() {
		return CREDITS_TRANSACTION_FEE_AMOUNT;
	}
	public void setCREDITS_TRANSACTION_FEE_AMOUNT(String cREDITS_TRANSACTION_FEE_AMOUNT) {
		CREDITS_TRANSACTION_FEE_AMOUNT = cREDITS_TRANSACTION_FEE_AMOUNT;
	}
	public String getDEBITS_PROCESSING_FEE_AMOUNT() {
		return DEBITS_PROCESSING_FEE_AMOUNT;
	}
	public void setDEBITS_PROCESSING_FEE_AMOUNT(String dEBITS_PROCESSING_FEE_AMOUNT) {
		DEBITS_PROCESSING_FEE_AMOUNT = dEBITS_PROCESSING_FEE_AMOUNT;
	}
	public String getDEBITS_TRANSACTION_FEE_AMOUNT() {
		return DEBITS_TRANSACTION_FEE_AMOUNT;
	}
	public void setDEBITS_TRANSACTION_FEE_AMOUNT(String dEBITS_TRANSACTION_FEE_AMOUNT) {
		DEBITS_TRANSACTION_FEE_AMOUNT = dEBITS_TRANSACTION_FEE_AMOUNT;
	}
	public String getCREDITS_AMOUNT() {
		return CREDITS_AMOUNT;
	}
	public void setCREDITS_AMOUNT(String cREDITS_AMOUNT) {
		CREDITS_AMOUNT = cREDITS_AMOUNT;
	}
	public String getCREDITS_REVERSAL_AMOUNT() {
		return CREDITS_REVERSAL_AMOUNT;
	}
	public void setCREDITS_REVERSAL_AMOUNT(String cREDITS_REVERSAL_AMOUNT) {
		CREDITS_REVERSAL_AMOUNT = cREDITS_REVERSAL_AMOUNT;
	}
	public String getDEBITS_AMOUNT() {
		return DEBITS_AMOUNT;
	}
	public void setDEBITS_AMOUNT(String dEBITS_AMOUNT) {
		DEBITS_AMOUNT = dEBITS_AMOUNT;
	}
	public String getDEBITS_REVERSAL_AMOUNT() {
		return DEBITS_REVERSAL_AMOUNT;
	}
	public void setDEBITS_REVERSAL_AMOUNT(String dEBITS_REVERSAL_AMOUNT) {
		DEBITS_REVERSAL_AMOUNT = dEBITS_REVERSAL_AMOUNT;
	}
	public String getORIGINAL_DATA_ELEMENTS() {
		return ORIGINAL_DATA_ELEMENTS;
	}
	public void setORIGINAL_DATA_ELEMENTS(String oRIGINAL_DATA_ELEMENTS) {
		ORIGINAL_DATA_ELEMENTS = oRIGINAL_DATA_ELEMENTS;
	}
	public String getFILE_UPDATE_CODE() {
		return FILE_UPDATE_CODE;
	}
	public void setFILE_UPDATE_CODE(String fILE_UPDATE_CODE) {
		FILE_UPDATE_CODE = fILE_UPDATE_CODE;
	}
	public String getFILE_SECURITY_CODE() {
		return FILE_SECURITY_CODE;
	}
	public void setFILE_SECURITY_CODE(String fILE_SECURITY_CODE) {
		FILE_SECURITY_CODE = fILE_SECURITY_CODE;
	}
	public String getRESPONSE_INDICATOR() {
		return RESPONSE_INDICATOR;
	}
	public void setRESPONSE_INDICATOR(String rESPONSE_INDICATOR) {
		RESPONSE_INDICATOR = rESPONSE_INDICATOR;
	}
	public String getSERVICE_INDICATOR() {
		return SERVICE_INDICATOR;
	}
	public void setSERVICE_INDICATOR(String sERVICE_INDICATOR) {
		SERVICE_INDICATOR = sERVICE_INDICATOR;
	}
	public String getREPLACEMENT_AMOUNTS() {
		return REPLACEMENT_AMOUNTS;
	}
	public void setREPLACEMENT_AMOUNTS(String rEPLACEMENT_AMOUNTS) {
		REPLACEMENT_AMOUNTS = rEPLACEMENT_AMOUNTS;
	}
	public String getMESSAGE_SECURITY_CODE() {
		return MESSAGE_SECURITY_CODE;
	}
	public void setMESSAGE_SECURITY_CODE(String mESSAGE_SECURITY_CODE) {
		MESSAGE_SECURITY_CODE = mESSAGE_SECURITY_CODE;
	}
	public String getAMOUNT_NET_SETTLEMENT() {
		return AMOUNT_NET_SETTLEMENT;
	}
	public void setAMOUNT_NET_SETTLEMENT(String aMOUNT_NET_SETTLEMENT) {
		AMOUNT_NET_SETTLEMENT = aMOUNT_NET_SETTLEMENT;
	}
	public String getPAYEE() {
		return PAYEE;
	}
	public void setPAYEE(String pAYEE) {
		PAYEE = pAYEE;
	}
	public String getSETTLEMENT_INSTITUTION_IDENT_CODE() {
		return SETTLEMENT_INSTITUTION_IDENT_CODE;
	}
	public void setSETTLEMENT_INSTITUTION_IDENT_CODE(String sETTLEMENT_INSTITUTION_IDENT_CODE) {
		SETTLEMENT_INSTITUTION_IDENT_CODE = sETTLEMENT_INSTITUTION_IDENT_CODE;
	}
	public String getRECEIVING_INSTITUTION_IDENT_CODE() {
		return RECEIVING_INSTITUTION_IDENT_CODE;
	}
	public void setRECEIVING_INSTITUTION_IDENT_CODE(String rECEIVING_INSTITUTION_IDENT_CODE) {
		RECEIVING_INSTITUTION_IDENT_CODE = rECEIVING_INSTITUTION_IDENT_CODE;
	}
	public String getFILE_NAME() {
		return FILE_NAME;
	}
	public void setFILE_NAME(String fILE_NAME) {
		FILE_NAME = fILE_NAME;
	}
	public String getACCOUNT_IDENTIFICATION_1() {
		return ACCOUNT_IDENTIFICATION_1;
	}
	public void setACCOUNT_IDENTIFICATION_1(String aCCOUNT_IDENTIFICATION_1) {
		ACCOUNT_IDENTIFICATION_1 = aCCOUNT_IDENTIFICATION_1;
	}
	public String getACCOUNT_IDENTIFICATION_2() {
		return ACCOUNT_IDENTIFICATION_2;
	}
	public void setACCOUNT_IDENTIFICATION_2(String aCCOUNT_IDENTIFICATION_2) {
		ACCOUNT_IDENTIFICATION_2 = aCCOUNT_IDENTIFICATION_2;
	}
	public String getTRANSACTION_DESCRIPTION() {
		return TRANSACTION_DESCRIPTION;
	}
	public void setTRANSACTION_DESCRIPTION(String tRANSACTION_DESCRIPTION) {
		TRANSACTION_DESCRIPTION = tRANSACTION_DESCRIPTION;
	}
	public String getRESERVED_ISO_USE_105() {
		return RESERVED_ISO_USE_105;
	}
	public void setRESERVED_ISO_USE_105(String rESERVED_ISO_USE_105) {
		RESERVED_ISO_USE_105 = rESERVED_ISO_USE_105;
	}
	public String getRESERVED_ISO_USE_106() {
		return RESERVED_ISO_USE_106;
	}
	public void setRESERVED_ISO_USE_106(String rESERVED_ISO_USE_106) {
		RESERVED_ISO_USE_106 = rESERVED_ISO_USE_106;
	}
	public String getRESERVED_ISO_USE_107() {
		return RESERVED_ISO_USE_107;
	}
	public void setRESERVED_ISO_USE_107(String rESERVED_ISO_USE_107) {
		RESERVED_ISO_USE_107 = rESERVED_ISO_USE_107;
	}
	public String getRESERVED_ISO_USE_108() {
		return RESERVED_ISO_USE_108;
	}
	public void setRESERVED_ISO_USE_108(String rESERVED_ISO_USE_108) {
		RESERVED_ISO_USE_108 = rESERVED_ISO_USE_108;
	}
	public String getRESERVED_ISO_USE_109() {
		return RESERVED_ISO_USE_109;
	}
	public void setRESERVED_ISO_USE_109(String rESERVED_ISO_USE_109) {
		RESERVED_ISO_USE_109 = rESERVED_ISO_USE_109;
	}
	public String getRESERVED_ISO_USE_110() {
		return RESERVED_ISO_USE_110;
	}
	public void setRESERVED_ISO_USE_110(String rESERVED_ISO_USE_110) {
		RESERVED_ISO_USE_110 = rESERVED_ISO_USE_110;
	}
	public String getRESERVED_ISO_USE_111() {
		return RESERVED_ISO_USE_111;
	}
	public void setRESERVED_ISO_USE_111(String rESERVED_ISO_USE_111) {
		RESERVED_ISO_USE_111 = rESERVED_ISO_USE_111;
	}
	public String getRESERVED_NATIONAL_USE_112() {
		return RESERVED_NATIONAL_USE_112;
	}
	public void setRESERVED_NATIONAL_USE_112(String rESERVED_NATIONAL_USE_112) {
		RESERVED_NATIONAL_USE_112 = rESERVED_NATIONAL_USE_112;
	}
	public String getRESERVED_NATIONAL_USE_113() {
		return RESERVED_NATIONAL_USE_113;
	}
	public void setRESERVED_NATIONAL_USE_113(String rESERVED_NATIONAL_USE_113) {
		RESERVED_NATIONAL_USE_113 = rESERVED_NATIONAL_USE_113;
	}
	public String getRESERVED_NATIONAL_USE_114() {
		return RESERVED_NATIONAL_USE_114;
	}
	public void setRESERVED_NATIONAL_USE_114(String rESERVED_NATIONAL_USE_114) {
		RESERVED_NATIONAL_USE_114 = rESERVED_NATIONAL_USE_114;
	}
	public String getRESERVED_NATIONAL_USE_115() {
		return RESERVED_NATIONAL_USE_115;
	}
	public void setRESERVED_NATIONAL_USE_115(String rESERVED_NATIONAL_USE_115) {
		RESERVED_NATIONAL_USE_115 = rESERVED_NATIONAL_USE_115;
	}
	public String getRESERVED_NATIONAL_USE_116() {
		return RESERVED_NATIONAL_USE_116;
	}
	public void setRESERVED_NATIONAL_USE_116(String rESERVED_NATIONAL_USE_116) {
		RESERVED_NATIONAL_USE_116 = rESERVED_NATIONAL_USE_116;
	}
	public String getRESERVED_NATIONAL_USE_117() {
		return RESERVED_NATIONAL_USE_117;
	}
	public void setRESERVED_NATIONAL_USE_117(String rESERVED_NATIONAL_USE_117) {
		RESERVED_NATIONAL_USE_117 = rESERVED_NATIONAL_USE_117;
	}
	public String getRESERVED_NATIONAL_USE_118() {
		return RESERVED_NATIONAL_USE_118;
	}
	public void setRESERVED_NATIONAL_USE_118(String rESERVED_NATIONAL_USE_118) {
		RESERVED_NATIONAL_USE_118 = rESERVED_NATIONAL_USE_118;
	}
	public String getRESERVED_NATIONAL_USE_119() {
		return RESERVED_NATIONAL_USE_119;
	}
	public void setRESERVED_NATIONAL_USE_119(String rESERVED_NATIONAL_USE_119) {
		RESERVED_NATIONAL_USE_119 = rESERVED_NATIONAL_USE_119;
	}
	public String getRESERVED_PRIVATE_USE_120() {
		return RESERVED_PRIVATE_USE_120;
	}
	public void setRESERVED_PRIVATE_USE_120(String rESERVED_PRIVATE_USE_120) {
		RESERVED_PRIVATE_USE_120 = rESERVED_PRIVATE_USE_120;
	}
	public String getRESERVED_PRIVATE_USE_121() {
		return RESERVED_PRIVATE_USE_121;
	}
	public void setRESERVED_PRIVATE_USE_121(String rESERVED_PRIVATE_USE_121) {
		RESERVED_PRIVATE_USE_121 = rESERVED_PRIVATE_USE_121;
	}
	public String getRESERVED_PRIVATE_USE_122() {
		return RESERVED_PRIVATE_USE_122;
	}
	public void setRESERVED_PRIVATE_USE_122(String rESERVED_PRIVATE_USE_122) {
		RESERVED_PRIVATE_USE_122 = rESERVED_PRIVATE_USE_122;
	}
	public String getRESERVED_PRIVATE_USE_123() {
		return RESERVED_PRIVATE_USE_123;
	}
	public void setRESERVED_PRIVATE_USE_123(String rESERVED_PRIVATE_USE_123) {
		RESERVED_PRIVATE_USE_123 = rESERVED_PRIVATE_USE_123;
	}
	public String getRESERVED_PRIVATE_USE_124() {
		return RESERVED_PRIVATE_USE_124;
	}
	public void setRESERVED_PRIVATE_USE_124(String rESERVED_PRIVATE_USE_124) {
		RESERVED_PRIVATE_USE_124 = rESERVED_PRIVATE_USE_124;
	}
	public String getRESERVED_PRIVATE_USE_125() {
		return RESERVED_PRIVATE_USE_125;
	}
	public void setRESERVED_PRIVATE_USE_125(String rESERVED_PRIVATE_USE_125) {
		RESERVED_PRIVATE_USE_125 = rESERVED_PRIVATE_USE_125;
	}
	public String getRESERVED_PRIVATE_USE_126() {
		return RESERVED_PRIVATE_USE_126;
	}
	public void setRESERVED_PRIVATE_USE_126(String rESERVED_PRIVATE_USE_126) {
		RESERVED_PRIVATE_USE_126 = rESERVED_PRIVATE_USE_126;
	}
	public String getRESERVED_PRIVATE_USE_127() {
		return RESERVED_PRIVATE_USE_127;
	}
	public void setRESERVED_PRIVATE_USE_127(String rESERVED_PRIVATE_USE_127) {
		RESERVED_PRIVATE_USE_127 = rESERVED_PRIVATE_USE_127;
	}
	public String getMAC_2() {
		return MAC_2;
	}
	public void setMAC_2(String mAC_2) {
		MAC_2 = mAC_2;
	}
	
	
	
}
